---
- name: "install apache"
  hosts:  dev
  tasks:
    - name: httpd
      yum:
        name: httpd
        state: present
    
    - name: start apache
      service:
        name: httpd
        state: started
